# https://github.com/Homebrew/homebrew-bundle

# For MS SQL tools, you need to accept the EULA
# HOMEBREW_ACCEPT_EULA=Y brew bundle

# Default target location for casks
cask_args appdir: "/Applications", require_sha: true

# System package tools
brew "mas" # Mac App Store CLI
brew "whalebrew" # Docker CLI for Homebrew

# Password manager
cask "bitwarden"

# Desktop utilities
cask "lunar" # Software monitor control via DDC
cask "balenaetcher"
cask "gimp"
cask "inkscape"
cask "slack"
cask "discord"

# Productivity
cask "google-chrome"
cask "zoom"
cask "microsoft-office"
cask "microsoft-teams"
cask "shapr3d"
cask "anytype"

# Containers
cask "docker"

# Nerd font for terminals and dev tools
cask "font-fira-code-nerd-font"

# Terminal tools
cask "iterm2"
cask "warp"
brew "rcm" # Dotfile management
brew "starship" # Fancy prompt

# Dev tools
whalebrew "whalebrew/wget"
brew "git"
cask "visual-studio-code"
cask "postman"
brew "terraform"
mas "WakeOnCommand", id: 1484204619

# Dev tools - Vantage
mas "Azure VPN Client", id: 1553936137
cask "microsoft-remote-desktop"
cask "git-credential-manager" # Supports Azure DevOps auth
cask "dotnet-sdk"
brew "azure-cli"
brew "sqlcmd"
cask "studio-3t"
