# Brew and Whalebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
path+=/opt/whalebrew/bin

# Force Docker to use the right images on M3
export DOCKER_DEFAULT_PLATFORM=linux/amd64

# Allow Mono to use assemblies installed from other Homebrew formulae
export MONO_GAC_PREFIX="/opt/homebrew"

# Python3 user package installations
path+=($HOME/Library/Python/3.9/bin)

# Dotnet global executables
path+=($HOME/.dotnet/tools)

# BCP utility from MSSQL tools
alias bcp='/opt/homebrew/Cellar/mssql-tools/17.10.1.1/bin/bcp'
